# This is the configuration file for GitHub issue templates.
# It defines the templates available for users to select when creating a new issue.
# For more information, see: https://docs.github.com/en/issues/creating-issues/creating-an-issue-template
# and https://docs.github.com/en/issues/creating-issues/creating-an-issue-template-using-a-template
# This file is in YAML format. Make sure to follow the correct syntax.

# Set to true to allow users to open a blank issue.
# Set to false to encourage users to use a template.
blank_issues_enabled: false



